### ISSUE TITLE
Mod compatibility / Filibuster Rhymes' Used Cars!

### ISSUE THREAD

**Issue by pimenta1807** [kwmx/ZomboidRCON#1]
I could help giving you the names of cars (commands) + png's of the mod "Filibuster Rhymes' Used Cars!"? 
Increasing spawn compatibility...
Perhaps a checkable option could unlock such options...

**Comment by kwmx** [comment]
Thank you for the feedback, the plan is to add a customizable database that would allow users to add custom vehicles and items this is still underworks and will be in the tools database dropdown menu.

Currently the program adds a database with the extension .zrdb for each server opened in it this DB can be viewed and edited using LiteDB if someone wants to urgently make changes.
