### ISSUE TITLE
Can't connect from outside IP

### ISSUE THREAD

**Issue by Talanthyr** [kwmx/ZomboidRCON#2]
(the router is ok...  other rcon software can connect to the server from anywhere)

When i use the true IP, i can't connect.  But when i use local IP (from the routeur... 192.168.*.* )  all is ok.  But other rcon software can connect, so the problem it's not the router or the server.

**Comment by kwmx** [comment]
Did you check the port?

**Comment by Talanthyr** [comment]
yes... and it's works with the IP (192.168......... from the routeur). but i want use from outside (with the real IP).

And i can send command by other rcon software.... so the problem is not my config.

**Comment by Vortal4** [comment]
Hi, doing the same thing for me, It doesn't work from the another computer in the same house.

**Comment by kwmx** [comment]
> Hi, doing the same thing for me, It doesn't work from the another computer in the same house.

Unfortunately I don't have much to go on to fix the issue. However, in your case check the firewall if it allows the app's connection through or not
