### ISSUE TITLE
Can't use setaccesslevel on my character

### ISSUE THREAD

**Issue by Mhikak** [kwmx/ZomboidRCON#6]
Hello ! I have a problem and I don't how to resolve it. I need to be an admin with my account and it doesn't allow me too. You can see in the picture what it tells me.

![image](https://github.com/kwmx/ZomboidRCON/assets/64315636/1d85ea66-09da-4787-bc86-ce9dbb185e43)

**Comment by kwmx** [comment]
Thank you for the feedback, I'll double check if the commands have been changed (on the server end)

**Comment by kwmx** [comment]
As of last test the issue can't be reproduced the issue will be closed please provide any more context to the issue.
